kind: pipeline
name: deploy_rpialert

steps:
  - name: deploy
    image: appleboy/drone-ssh
    when:
      branch:
        - master
      event:
        - push
    settings:
      host: lp13.rpiambulance.com
      username: drone
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - docker-compose -f /drone/docker-compose.yml up -d --build rpialert

  - name: deploy-dev
    image: appleboy/drone-ssh
    when:
      branch:
        - dev
      event:
        - push
    settings:
      host: lp13.rpiambulance.com
      username: drone
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - docker-compose -f /drone/docker-compose.yml up -d --build rpialert-dev
