kind: pipeline
name: deploy_rpialert

steps:
  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: lp12.rpiambulance.com
      username: drone
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - docker-compose -f /drone/docker-compose.yml up -d --build rpialert
      when:
        branch:
          - master
        event:
          - push

  - name: deploy-dev
    image: appleboy/drone-ssh
    settings:
      host: lp12.rpiambulance.com
      username: drone
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - docker-compose -f /drone/docker-compose.yml up -d --build rpialert-dev
      when:
        branch:
          - dev
        event:
          - push
